### ISSUE TITLE
data analysis of defintion

### ISSUE THREAD

**Issue by madebygps** [learntocloud/define-the-cloud#189]
- most popular definitons by tag by month
- most popular month of contributions
- and any other ones you want to add

**Comment by madebygps** [comment]
@rishp66

**Comment by rishp66** [comment]
Additional Stuff:

- after i create the ones for definitions, I'll make one for the daily definitions as well
 - ex: what days were most contributed out of the day
 - most popular categories, etc.

**Comment by rishp66** [comment]
completed making a sentiment analysis of each definition within the database using NTLK library

**Comment by rishp66** [comment]
will now group by tag and then will perform contribution by authors and aggregate for # of contributions made by author and their individual sentiment analysis before moving onto time section

**Comment by rishp66** [comment]
### issue with graphing on streamlit 
```
# Set a dark background style for Seaborn
sns.set(style='darkgrid')

plt.figure(figsize=(10, 6))
sns.barplot(x='sentiment_score', y='tag', data=sentiment_by_tag, palette='viridis')
plt.title('Sentiment Scores by Tag')
plt.show()

# setting warning message to false 
st.set_option('deprecation.showPyplotGlobalUse', False)
st.pyplot()
```

With the following code, I need to create a horizontal bar chart comparing the sentiment of each tag. In this case, I have done it with Seaborn so I'll continue doing that but I cannot find anything for a horizontal bar chart that would work. I tried looking it up [here](https://github.com/streamlit/streamlit/issues/716) let me know if you find anything

**Comment by madebygps** [comment]
amazing work tracking the progress Rish!!! @rishp66

**Comment by rishp66** [comment]
@madebygps thanks! just added some new graphs and stuff -- going to work on authors next :)

**Comment by rishp66** [comment]
finished the first introductory page for authors, had to take a break cuz of exams going on for uni -- gonna finish sentiment analysis soon for the authors & then move onto final portion of time

**Comment by rishp66** [comment]
Completed the Authors page after some time haha

**Comment by rishp66** [comment]
FInished reimporting libraries & now working on Time page - will be done hopefully soon 🤞

**Comment by rishp66** [comment]
Got some time to work on the project and all pages are now done but there is an issue.

**The project can only be run on localhost.**

I have had significant issues trying to deploy this utilizing many help pages and online resources from the Streamlit docs, trying out Azure documentation and refactoring the code. 
It will not take the credentials necessary to deploy it on the Streamlit cloud.
Here is the link to the GitHub repo: [https://github.com/rishp66/dictionary_analysis](https://github.com/rishp66/dictionary_analysis)

![Screenshot 2024-06-16 at 11 12 18 AM](https://github.com/learntocloud/define-the-cloud/assets/63080953/b541d68f-e0a7-4aed-bd2f-f9869a2e9216)

**Comment by rishp66** [comment]
Above, there is the error code statement.

**Comment by madebygps** [comment]
@rishabkumar7 you're a bit more familiar with streamlit+python. Have you seen this error? If not @rishp66  we can do a debugging session on l2c discord to work through this.

**Comment by rishabkumar7** [comment]
@rishp66 are you trying to deploy it to Azure or Streamlit cloud, or you tried both and got the error.
Also, the second screenshot, where is that from?

**Comment by rishp66** [comment]
@rishabkumar7  I've only tried to deploy to streamlit cloud so far. There's only 1 screenshot, it's the same error page. 

@madebygps Yeah, we can do debugging session. Tbh, it's just that the st.secrets() is not taking the secrets I input that work fine within the TOML file on local

**Comment by rishabkumar7** [comment]
@rishp66 and you are adding it in the advanced settings on Streamlit cloud interface?
![image](https://github.com/learntocloud/define-the-cloud/assets/45825464/da00910a-ac11-43bd-9ffa-6afacb127668)

I think it would we easier to debug on a discord call.

**Comment by rishp66** [comment]
@rishabkumar7 i'll send you a message on the discord

**Comment by rishp66** [comment]
Reconfiguring and deploying container with datadefinedcloud to Docker Hub with this command:
`docker buildx build --platform linux/amd64 -t datadefinedcloud .`

**Comment by rishabkumar7** [comment]
So. you need to make sure, your docker image is built for `linux/amd64`

**Comment by rishp66** [comment]
See new Docker image here:
[docker.io/rp999/datadefinedcloud](url)

**Comment by rishabkumar7** [comment]
The link doesn't work.

**Comment by rishp66** [comment]
fixed it :)

**Comment by rishabkumar7** [comment]
Yep, try deploying now, it should work.

**Comment by rishp66** [comment]
That took about 3-4 hours so probably will work on deploying it to ACR later

**Comment by rishp66** [comment]
Completed deployment to ACR: 
[https://portal.azure.com/#@gwynethpenaoutlook.onmicrosoft.com/resource/subscriptions/96e40cb1-d5eb-46c6-b0fd-8e64eb9c119d/resourceGroups/definethecloudsentiment-rg/providers/Microsoft.App/containerapps/datadefinedcloud/containerapp](datadefinedcloud)

**Comment by madebygps** [comment]
i removed your link, it has sub id in it, be careful with that moving forward

**Comment by rishp66** [comment]
oh i see, my bad on that one :(

**Comment by rishabkumar7** [comment]
@rishp66 let me know once we have the ACA deployed.
Also, if you run into issue, feel free to reach out.

**Comment by rishp66** [comment]
@rishabkumar7 The container app is up and running and can be accessed via a URL however it encounters an error after you put in the URL

**Comment by rishp66** [comment]
ServiceRequestError: No connection adapters were found for [application url]

**Comment by madebygps** [comment]
what troubleshooting steps have you tried?

**Comment by rishabkumar7** [comment]
@rishp66 My thoughts:
So by default ACA ingress listens on port 443. For your container are you using the default streamlit port 8501?
If yes, add that as the target port in ACA settings. You can find that in the `Ingress` tab.
<img width="761" alt="Screenshot 2024-06-27 at 9 35 53 AM" src="https://github.com/learntocloud/define-the-cloud/assets/45825464/bc0737d2-b38f-4061-9a38-83a461ab5348">

**Comment by rishp66** [comment]
> what troubleshooting steps have you tried?

I was on vacation since the 28th but I believe I tried looking at some websites:
https://www.slingacademy.com/article/fixing-python-requests-error-no-connection-adapters/
https://stackoverflow.com/questions/58866979/python-no-connection-adapters-were-found

Neither of these and the ones I found were I think relevant to the issue here.

**Comment by rishp66** [comment]
@rishabkumar7 Ahhh I see, okay, I will change that when I can and follow up with an update on how it's going.

**Comment by rishp66** [comment]
@rishabkumar7 I checked it out, and I reconfigured the target ports has been changed to 8501 but the same error appears of 
**ServiceRequestError: No connection adapters were found for [application url]**

**Comment by rishp66** [comment]
Within looking at the error codes, it has something to do within the Azure Core library within the pipeline file. I did not find any relevant articles explaining how to perform anything regarding this error so I used Claude. It had said that it had something with the SDK being out of date so I performed the following command: 

`pip3 install --upgrade azure-cosmos`

**Comment by rishp66** [comment]
This stated that all requirements were already satisfied. However, I am unsure as what to do further since the only other options it gives are importing the requests library which I do not believe is necessary or changing network/firewall settings on the CosmosDB resource.

**Comment by madebygps** [comment]
closing, feel free to reopen when relevant
